-- ############################
-- Parallax Official Schema
--
-- https://snowlynxsoftware.net 
--
-- Copyright 2025. Snow Lynx Software, LLC. All Rights Reserved.
-- ############################

-- AUTH

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "email" TEXT UNIQUE NOT NULL,
    "display_name" TEXT NOT NULL,
    "avatar_url" TEXT,
    "profile_text" TEXT,
    "is_verified" BOOLEAN DEFAULT false,
    "password_hash" TEXT,
    "last_login" TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON "users" ("email");

CREATE TABLE IF NOT EXISTS "user_login_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "user_id" INTEGER REFERENCES users(id) ON DELETE CASCADE
);

-- // USERS
INSERT INTO public.users (email, display_name)
VALUES ('snowlynxsoftware@gmail.com', 'SNOW')
ON CONFLICT (id) DO NOTHING;

-- // SETTINGS

CREATE TABLE IF NOT EXISTS "app_settings" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,  
    "allow_registrations" BOOLEAN DEFAULT true,
    "allow_send_emails" BOOLEAN DEFAULT false,
    "is_maintenance_mode" BOOLEAN DEFAULT false,
    "maintenance_mode_message" BOOLEAN DEFAULT false,
    "feature_flags" JSONB DEFAULT '{}'
);


-- Create feature_flags table
CREATE TABLE IF NOT EXISTS "feature_flags" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "is_archived" BOOLEAN DEFAULT false,
    "key" TEXT UNIQUE NOT NULL,
    "enabled" BOOLEAN DEFAULT false,
    "description" TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_feature_flags_key ON "feature_flags" ("key");
CREATE INDEX IF NOT EXISTS idx_feature_flags_enabled ON "feature_flags" ("enabled");

-- Remove old feature_flags column from app_settings (cleanup)
ALTER TABLE app_settings DROP COLUMN IF EXISTS feature_flags;

-- Insert initial feature flags
INSERT INTO feature_flags (key, enabled, description)
VALUES
    ('prelaunch_mode', true, 'When enabled, prevents new user registrations while showing welcome/coming soon page')
ON CONFLICT (key) DO NOTHING;